"""Static page-server routes — landing / terminal / bridge / undelivered / version.

server.py decomposition (BR-CODE-1). Thin FileResponse/RedirectResponse servers
+ the terminal/bridge path-catch-all proxies (path-traversal guarded). Factory
takes the static dir + getters for the two patched server symbols
(STOREFRONT_AS_LANDING, _STOREFRONT_VERSION) so the route tests keep binding.
"""
from __future__ import annotations

import os
from typing import Callable

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, RedirectResponse


def build_pages_router(
    static_dir: str,
    *,
    get_storefront_as_landing: Callable[[], bool] = lambda: False,
    get_storefront_version: Callable[[], str] = lambda: "dev",
    get_bridge_dir: Callable[[], str],
) -> APIRouter:
    # get_bridge_dir resolves the test-patched server symbol (app._BRIDGE_DIR)
    # at request time — not captured at mount time — so the route tests'
    # monkeypatch binds. It is required (no default) because the bridge dir is
    # only meaningful relative to the live server module.
    router = APIRouter()

    @router.get("/")
    def root_landing():
        """Unified frontend homescreen / hub (D0, operator directive 2026-05-15 bot_chat #157).
        5 cards: Terminal (broker) / Undelivered (CS+fulfillment) / Orders (D2) /
        Store (public) / Bridge (D4). Served at / as the Render landing (the
        vibepass-storefront-test web service runs uvicorn server:app with
        STOREFRONT_AS_LANDING=false; the static CDN's static/index.html redirects
        / → /home/ to the same hub).
        get_storefront_as_landing()=true keeps the old customer-only redirect to /store.
        Liveness moved to /healthz (always was the real Render check path).
        """
        if get_storefront_as_landing():
            return RedirectResponse(url="/store", status_code=302)
        return FileResponse(os.path.join(static_dir, "home", "index.html"))


    @router.get("/home")
    def home_landing_redirect():
        """Bounce bare /home → /home/ so the terminal's ← HUB button (nav.js,
        href=/home/) resolves the same on the FastAPI shell as on the static CDN
        (publishPath=static serves /home/index.html for the directory form)."""
        return RedirectResponse(url="/home/", status_code=308)


    @router.get("/home/")
    def home_landing():
        """Serve the unified landing selector at the explicit /home/ path. The
        static CDN serves static/home/index.html here natively; this route gives
        the FastAPI shell parity so HUB → /home/ never 404s regardless of which
        surface (terminal-test CDN vs storefront-test shell) served the page."""
        return FileResponse(os.path.join(static_dir, "home", "index.html"))


    @router.get("/terminal")
    def terminal_landing():
        """Bounce bare /terminal → /terminal/ (trailing slash) so the relative
        nav targets generated by nav.js (event.html, movers.html, etc.) resolve
        UNDER /terminal/ instead of falling out to root.

        Without the trailing slash, the browser treats /terminal as a non-directory
        URL and resolves <a href="event.html"> against the parent → /event.html,
        which 404s on this unified shell. PR #165 made the nav.js hrefs relative
        so the same bundle works on the terminal-test CDN (publishPath at root)
        AND under FastAPI mount — this redirect supplies the directory context
        the relative resolution needs on the FastAPI side."""
        return RedirectResponse(url="/terminal/", status_code=308)


    @router.get("/terminal/")
    def terminal_index():
        """Serve the terminal home (index.html). Same content as the bare /terminal
        redirect target — kept as a distinct handler so the route exists explicitly
        and nav.js's `./` (home) link doesn't fall through to the {page:path} catch-all
        with an empty page string (FastAPI matches it here first)."""
        return FileResponse(os.path.join(static_dir, "terminal", "index.html"))


    @router.get("/terminal/{page:path}")
    def terminal_static_proxy(page: str, request: Request):
        """Proxy /terminal/<anything> → static/terminal/<anything> so the unified
        shell (PR #168 testing-unified architecture) keeps nav.js relative-path
        navigation working without a separate URL scheme.

        Without this route, opening https://<storefront-test>/terminal/event.html
        returns 404 because StaticFiles is only mounted at /static, not /terminal.
        Adding this proxy means nav.js's relative <a href="event.html"> from the
        /terminal/ landing resolves to /terminal/event.html → here → 200 from the
        static file. Same applies to all sibling pages (movers/performer/orders/
        login) plus the lib/ subtree (uplot, supabase, etc.).

        Security: validates `page` against path traversal + restricts to known
        extensions so the proxy can't be turned into an arbitrary-file reader."""
        if not page or page in ("", "/"):  # pragma: no cover - shadowed by the explicit /terminal/ index route
            return FileResponse(os.path.join(static_dir, "terminal", "index.html"))
        # Fantasy was spun off from the terminal into the D5 /fantasy/ surface
        # (no longer a terminal tab). Redirect the old page URL so bookmarks +
        # any stale deep-links (…/terminal/fantasy.html?league=5) keep resolving.
        if page == "fantasy.html":
            qs = ("?" + request.url.query) if request.url.query else ""
            return RedirectResponse(url="/fantasy/" + qs, status_code=308)
        if ".." in page or page.startswith("/") or "\\" in page:
            raise HTTPException(404, "not found")
        # Whitelist extensions — proxy serves UI bundle pieces only, never
        # arbitrary files that might land under static/terminal/ in the future.
        if not page.lower().endswith((".html", ".css", ".js", ".map",
                                       ".svg", ".png", ".jpg", ".jpeg",
                                       ".ico", ".woff", ".woff2", ".webp")):
            raise HTTPException(404, "not found")
        full_path = os.path.join(static_dir, "terminal", page)
        if not os.path.isfile(full_path):
            raise HTTPException(404, "not found")
        return FileResponse(full_path)


    # --- D5 / Fantasy ----------------------------------------------------------
    # Fantasy was promoted out of the D0 terminal into its own hub surface
    # (operator directive 2026-07-08 — "make it d5 … put it in the hub"). Served
    # from static/fantasy/ under the same shell as the terminal, mirroring the
    # /terminal proxy pattern (landing redirect + index + extension-whitelisted,
    # traversal-guarded asset proxy). Reuses the terminal's shared libs via
    # absolute /static/terminal/ refs, so no assets are duplicated.

    @router.get("/fantasy")
    def fantasy_landing():
        """Bounce bare /fantasy → /fantasy/ so the surface resolves under its
        directory prefix (same reasoning as /terminal)."""
        return RedirectResponse(url="/fantasy/", status_code=308)


    @router.get("/fantasy/")
    def fantasy_index():
        """Serve the D5 fantasy surface shell (static/fantasy/index.html)."""
        return FileResponse(os.path.join(static_dir, "fantasy", "index.html"))


    @router.get("/fantasy/{page:path}")
    def fantasy_static_proxy(page: str):
        """Proxy /fantasy/<anything> → static/fantasy/<anything> (boot.js, etc.).
        Path-traversal guarded + extension-whitelisted, matching the /terminal
        proxy. Shared libs load from /static/terminal/ via the StaticFiles mount,
        so only fantasy-owned assets live under this dir."""
        if not page or page in ("", "/"):  # pragma: no cover - shadowed by the explicit /fantasy/ index route
            return FileResponse(os.path.join(static_dir, "fantasy", "index.html"))
        if ".." in page or page.startswith("/") or "\\" in page:
            raise HTTPException(404, "not found")
        if not page.lower().endswith((".html", ".css", ".js", ".map",
                                       ".svg", ".png", ".jpg", ".jpeg",
                                       ".ico", ".woff", ".woff2", ".webp")):
            raise HTTPException(404, "not found")
        full_path = os.path.join(static_dir, "fantasy", page)
        if not os.path.isfile(full_path):
            raise HTTPException(404, "not found")
        return FileResponse(full_path)


    @router.get("/undelivered")
    def undelivered_landing():
        """CS fulfillment + sales tracking entry (scaffold — D2 to fill, bot_chat #179).
        Spec: design/undelivered-window-2026-05-08.md."""
        return FileResponse(os.path.join(static_dir, "undelivered", "index.html"))


    # --- D4 / Exos (Bridge) ----------------------------------------------------
    # Serve the d4_bridge Vite SPA from this Railway app — same origin as the hub,
    # Terminal, Store, and Undelivered (PR #318 — Railway is now the primary host).
    # Landing redirect, index handler, path-catch-all for assets + SPA deep links.
    # App is built with Vite base '/bridge/' (vite.config.ts) and
    # <BrowserRouter basename="/bridge">, so asset refs + client routes resolve
    # under this prefix. Build artifact: static/bridge/ (rebuild via
    # `npm --prefix d4_bridge run build` then copy dist → static/bridge/).
    # Same-origin means the Supabase session in localStorage is shared with the
    # hub — a user signed in on the home page is automatically signed into Bridge.
    # Returns 404 cleanly until the build artifact is present.
    # (bridge dir resolved at request time via get_bridge_dir() — patchable.)


    @router.get("/bridge")
    def bridge_landing():
        """Bounce bare /bridge → /bridge/ so the SPA's relative + basename routing
        resolves under the directory prefix (same reasoning as /terminal)."""
        return RedirectResponse(url="/bridge/", status_code=308)


    @router.get("/bridge/")
    def bridge_index():
        """Serve the Exos/Bridge SPA shell. 404 (not 500) when the build isn't
        present yet, so the route is safe to ship ahead of the first dist copy."""
        index_path = os.path.join(get_bridge_dir(), "index.html")
        if not os.path.isfile(index_path):
            raise HTTPException(404, "bridge build not present — run `npm --prefix d4_bridge run build` then copy dist → static/bridge/")
        return FileResponse(index_path)


    @router.get("/bridge/{page:path}")
    def bridge_static_proxy(page: str):
        """Proxy /bridge/<anything> → static/bridge/<anything>. SPA deep links
        (/bridge/event/123 etc.) fall back to index.html for client-side routing.
        Path-traversal guarded + extension-whitelisted (UI bundle pieces only)."""
        if not page or page in ("", "/"):  # pragma: no cover - shadowed by the explicit /bridge/ index route
            index_path = os.path.join(get_bridge_dir(), "index.html")
            if not os.path.isfile(index_path):
                raise HTTPException(404, "bridge build not present")
            return FileResponse(index_path)
        if ".." in page or page.startswith("/") or "\\" in page:
            raise HTTPException(404, "not found")
        full_path = os.path.join(get_bridge_dir(), page)
        # Real asset → serve it. Whitelist mirrors the /terminal proxy.
        if page.lower().endswith((".html", ".css", ".js", ".map", ".json",
                                   ".svg", ".png", ".jpg", ".jpeg", ".ico",
                                   ".woff", ".woff2", ".webp", ".txt")):
            if not os.path.isfile(full_path):
                raise HTTPException(404, "not found")
            return FileResponse(full_path)
        # Non-asset path (a client route like /bridge/my-tickets) → SPA shell.
        index_path = os.path.join(get_bridge_dir(), "index.html")
        if not os.path.isfile(index_path):
            raise HTTPException(404, "bridge build not present")
        return FileResponse(index_path)


    @router.get("/version.json")
    def version_json():
        """Public deploy-version endpoint — same get_storefront_version() the cache-bust
        pipeline uses, plus the resolution chain that produced it, plus a deploy
        indicator from common Render/Railway env vars. Consumed by nav.js's
        version chip (PR #184) so terminal pages render a real SHA in the topbar
        even though they don't go through _read_storefront_html (which only
        rewrites store pages). Cheap; safe to call cross-origin."""
        return {
            "version": get_storefront_version(),
            "render_commit": os.environ.get("RENDER_GIT_COMMIT") or None,
            "railway_commit": os.environ.get("RAILWAY_GIT_COMMIT_SHA") or None,
            "git_commit": os.environ.get("GIT_COMMIT") or None,
            "render_service_id": os.environ.get("RENDER_SERVICE_ID") or None,
            "render_external_url": os.environ.get("RENDER_EXTERNAL_URL") or None,
            "railway_public_domain": os.environ.get("RAILWAY_PUBLIC_DOMAIN") or None,
            "deployed_at_iso": os.environ.get("RENDER_GIT_COMMIT_TIME") or None,
        }

    return router
