"""Static page-server routes — landing / terminal / bridge / undelivered / version.

server.py decomposition (BR-CODE-1). Thin FileResponse/RedirectResponse servers
+ the terminal/bridge path-catch-all proxies (path-traversal guarded). Factory
takes the static dir + getters for the two patched server symbols
(STOREFRONT_AS_LANDING, _STOREFRONT_VERSION) so the route tests keep binding.
"""
from __future__ import annotations

import html as _html
import json
import os
import re
from typing import Callable

import requests
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, RedirectResponse, Response


def build_pages_router(
    static_dir: str,
    *,
    get_storefront_as_landing: Callable[[], bool] = lambda: False,
    get_storefront_version: Callable[[], str] = lambda: "dev",
    get_bridge_dir: Callable[[], str],
    get_supabase_url: Callable[[], str | None] = lambda: None,
    get_supabase_anon_key: Callable[[], str | None] = lambda: None,
) -> APIRouter:
    # get_bridge_dir resolves the test-patched server symbol (app._BRIDGE_DIR)
    # at request time — not captured at mount time — so the route tests'
    # monkeypatch binds. It is required (no default) because the bridge dir is
    # only meaningful relative to the live server module.
    router = APIRouter()

    @router.get("/")
    def root_landing():
        """Unified frontend homescreen / hub (D0, operator directive 2026-05-15 bot_chat #157).
        5 cards: Terminal (broker) / Undelivered (CS+fulfillment) / Orders (D2) /
        Store (public) / Bridge (D4). Served at / as the Render landing (the
        vibepass-storefront-test web service runs uvicorn server:app with
        STOREFRONT_AS_LANDING=false; the static CDN's static/index.html redirects
        / → /home/ to the same hub).
        get_storefront_as_landing()=true keeps the old customer-only redirect to /store.
        Liveness moved to /healthz (always was the real Render check path).
        """
        if get_storefront_as_landing():
            return RedirectResponse(url="/store", status_code=302)
        return FileResponse(os.path.join(static_dir, "home", "index.html"))


    @router.get("/home")
    def home_landing_redirect():
        """Bounce bare /home → /home/ so the terminal's ← HUB button (nav.js,
        href=/home/) resolves the same on the FastAPI shell as on the static CDN
        (publishPath=static serves /home/index.html for the directory form)."""
        return RedirectResponse(url="/home/", status_code=308)


    @router.get("/home/")
    def home_landing():
        """Serve the unified landing selector at the explicit /home/ path. The
        static CDN serves static/home/index.html here natively; this route gives
        the FastAPI shell parity so HUB → /home/ never 404s regardless of which
        surface (terminal-test CDN vs storefront-test shell) served the page."""
        return FileResponse(os.path.join(static_dir, "home", "index.html"))


    @router.get("/terminal")
    def terminal_landing():
        """Bounce bare /terminal → /terminal/ (trailing slash) so the relative
        nav targets generated by nav.js (event.html, movers.html, etc.) resolve
        UNDER /terminal/ instead of falling out to root.

        Without the trailing slash, the browser treats /terminal as a non-directory
        URL and resolves <a href="event.html"> against the parent → /event.html,
        which 404s on this unified shell. PR #165 made the nav.js hrefs relative
        so the same bundle works on the terminal-test CDN (publishPath at root)
        AND under FastAPI mount — this redirect supplies the directory context
        the relative resolution needs on the FastAPI side."""
        return RedirectResponse(url="/terminal/", status_code=308)


    @router.get("/terminal/")
    def terminal_index():
        """Serve the terminal home (index.html). Same content as the bare /terminal
        redirect target — kept as a distinct handler so the route exists explicitly
        and nav.js's `./` (home) link doesn't fall through to the {page:path} catch-all
        with an empty page string (FastAPI matches it here first)."""
        return FileResponse(os.path.join(static_dir, "terminal", "index.html"))


    @router.get("/terminal/{page:path}")
    def terminal_static_proxy(page: str, request: Request):
        """Proxy /terminal/<anything> → static/terminal/<anything> so the unified
        shell (PR #168 testing-unified architecture) keeps nav.js relative-path
        navigation working without a separate URL scheme.

        Without this route, opening https://<storefront-test>/terminal/event.html
        returns 404 because StaticFiles is only mounted at /static, not /terminal.
        Adding this proxy means nav.js's relative <a href="event.html"> from the
        /terminal/ landing resolves to /terminal/event.html → here → 200 from the
        static file. Same applies to all sibling pages (movers/performer/orders/
        login) plus the lib/ subtree (uplot, supabase, etc.).

        Security: validates `page` against path traversal + restricts to known
        extensions so the proxy can't be turned into an arbitrary-file reader."""
        if not page or page in ("", "/"):  # pragma: no cover - shadowed by the explicit /terminal/ index route
            return FileResponse(os.path.join(static_dir, "terminal", "index.html"))
        # Fantasy was spun off from the terminal into the D5 /fantasy/ surface
        # (no longer a terminal tab). Redirect the old page URL so bookmarks +
        # any stale deep-links (…/terminal/fantasy.html?league=5) keep resolving.
        if page == "fantasy.html":
            qs = ("?" + request.url.query) if request.url.query else ""
            return RedirectResponse(url="/fantasy/" + qs, status_code=308)
        if ".." in page or page.startswith("/") or "\\" in page:
            raise HTTPException(404, "not found")
        # Whitelist extensions — proxy serves UI bundle pieces only, never
        # arbitrary files that might land under static/terminal/ in the future.
        if not page.lower().endswith((".html", ".css", ".js", ".map",
                                       ".svg", ".png", ".jpg", ".jpeg",
                                       ".ico", ".woff", ".woff2", ".webp")):
            raise HTTPException(404, "not found")
        full_path = os.path.join(static_dir, "terminal", page)
        if not os.path.isfile(full_path):
            raise HTTPException(404, "not found")
        return FileResponse(full_path)


    # --- D5 / Fantasy ----------------------------------------------------------
    # Fantasy was promoted out of the D0 terminal into its own hub surface
    # (operator directive 2026-07-08 — "make it d5 … put it in the hub"). Served
    # from static/fantasy/ under the same shell as the terminal, mirroring the
    # /terminal proxy pattern (landing redirect + index + extension-whitelisted,
    # traversal-guarded asset proxy). Reuses the terminal's shared libs via
    # absolute /static/terminal/ refs, so no assets are duplicated.

    @router.get("/fantasy")
    def fantasy_landing():
        """Bounce bare /fantasy → /fantasy/ so the surface resolves under its
        directory prefix (same reasoning as /terminal)."""
        return RedirectResponse(url="/fantasy/", status_code=308)


    @router.get("/fantasy/")
    def fantasy_index():
        """Serve the D5 fantasy surface shell (static/fantasy/index.html)."""
        return FileResponse(os.path.join(static_dir, "fantasy", "index.html"))


    @router.get("/fantasy/{page:path}")
    def fantasy_static_proxy(page: str):
        """Proxy /fantasy/<anything> → static/fantasy/<anything> (boot.js, etc.).
        Path-traversal guarded + extension-whitelisted, matching the /terminal
        proxy. Shared libs load from /static/terminal/ via the StaticFiles mount,
        so only fantasy-owned assets live under this dir."""
        if not page or page in ("", "/"):  # pragma: no cover - shadowed by the explicit /fantasy/ index route
            return FileResponse(os.path.join(static_dir, "fantasy", "index.html"))
        if ".." in page or page.startswith("/") or "\\" in page:
            raise HTTPException(404, "not found")
        if not page.lower().endswith((".html", ".css", ".js", ".map",
                                       ".svg", ".png", ".jpg", ".jpeg",
                                       ".ico", ".woff", ".woff2", ".webp")):
            raise HTTPException(404, "not found")
        full_path = os.path.join(static_dir, "fantasy", page)
        if not os.path.isfile(full_path):
            raise HTTPException(404, "not found")
        return FileResponse(full_path)


    @router.get("/undelivered")
    def undelivered_landing():
        """CS fulfillment + sales tracking entry (scaffold — D2 to fill, bot_chat #179).
        Spec: design/undelivered-window-2026-05-08.md."""
        return FileResponse(os.path.join(static_dir, "undelivered", "index.html"))


    # --- D4 / Exos (Bridge) ----------------------------------------------------
    # Serve the d4_bridge Vite SPA from this Railway app — same origin as the hub,
    # Terminal, Store, and Undelivered (PR #318 — Railway is now the primary host).
    # Landing redirect, index handler, path-catch-all for assets + SPA deep links.
    # App is built with Vite base '/bridge/' (vite.config.ts) and
    # <BrowserRouter basename="/bridge">, so asset refs + client routes resolve
    # under this prefix. Build artifact: static/bridge/ (rebuild via
    # `npm --prefix d4_bridge run build` then copy dist → static/bridge/).
    # Same-origin means the Supabase session in localStorage is shared with the
    # hub — a user signed in on the home page is automatically signed into Bridge.
    # Returns 404 cleanly until the build artifact is present.
    # (bridge dir resolved at request time via get_bridge_dir() — patchable.)


    @router.get("/bridge")
    def bridge_landing():
        """Bounce bare /bridge → /bridge/ so the SPA's relative + basename routing
        resolves under the directory prefix (same reasoning as /terminal)."""
        return RedirectResponse(url="/bridge/", status_code=308)


    @router.get("/bridge/")
    def bridge_index():
        """Serve the Exos/Bridge SPA shell. 404 (not 500) when the build isn't
        present yet, so the route is safe to ship ahead of the first dist copy."""
        index_path = os.path.join(get_bridge_dir(), "index.html")
        if not os.path.isfile(index_path):
            raise HTTPException(404, "bridge build not present — run `npm --prefix d4_bridge run build` then copy dist → static/bridge/")
        return FileResponse(index_path)


    # --- D4 / Exos: crawler-visible event pages + events sitemap (Stage 5) -----
    # The SPA sets Event JSON-LD at runtime (d4_bridge/src/lib/meta.ts), which
    # Googlebot reads only when it chooses to render JS. The Google Events rich
    # result (Search + Maps) is the organizer's free distribution channel, so
    # /bridge/event/<id> now ships the JSON-LD + Open Graph tags in the initial
    # HTML for EVERY caller: one anon read of exos_public_events (published
    # events only — the view is security_invoker, so drafts never leak), a 2s
    # budget, and the untouched SPA shell on any failure. Same-origin, no key
    # beyond the publishable anon key. /bridge/sitemap-events.xml lists every
    # published event with <lastmod> for Search Console.

    _UUID_RE = re.compile(r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
    _PUBLIC_EVENT_COLS = ("id,name,slug,description,starts_at,ends_at,doors_at,timezone,currency,"
                          "venue_name,venue_address,performer_names,image_url,total_tickets,"
                          "tickets_sold,google_place_id,venue_lat,venue_lng,updated_at")

    def _bridge_public_base(request: Request) -> str:
        # Honour the proxy-supplied scheme/host (Render/Railway terminate TLS).
        proto = request.headers.get("x-forwarded-proto") or request.url.scheme or "https"
        host = request.headers.get("x-forwarded-host") or request.headers.get("host") or request.url.netloc
        return f"{proto}://{host}/bridge"

    def _bridge_rest(path: str, params: dict) -> list | None:
        url, key = get_supabase_url(), get_supabase_anon_key()
        if not url or not key:
            return None
        r = requests.get(f"{url}/rest/v1/{path}", params=params,
                         headers={"apikey": key, "Authorization": f"Bearer {key}"}, timeout=2.0)
        if r.status_code != 200:
            return None
        data = r.json()
        return data if isinstance(data, list) else None

    def _bridge_event_json_ld(ev: dict, base: str) -> dict:
        addr = ev.get("venue_address") or {}
        if not isinstance(addr, dict):
            addr = {}
        place: dict = {"@type": "Place", "name": ev.get("venue_name") or ""}
        postal = {k: v for k, v in {
            "streetAddress": addr.get("street"), "addressLocality": addr.get("city"),
            "addressRegion": addr.get("region"), "postalCode": addr.get("postal"),
            "addressCountry": addr.get("country"),
        }.items() if v}
        if postal:
            place["address"] = {"@type": "PostalAddress", **postal}
        lat, lng, pid = ev.get("venue_lat"), ev.get("venue_lng"), ev.get("google_place_id")
        if lat is not None and lng is not None:
            place["geo"] = {"@type": "GeoCoordinates", "latitude": float(lat), "longitude": float(lng)}
            place["hasMap"] = (f"https://www.google.com/maps/search/?api=1&query={float(lat)},{float(lng)}"
                               + (f"&query_place_id={pid}" if pid else ""))
        elif pid:
            place["hasMap"] = f"https://www.google.com/maps/place/?q=place_id:{pid}"
        if pid:
            place["identifier"] = pid
        url = f"{base}/event/{ev['id']}"
        remaining = max(0, int(ev.get("total_tickets") or 0) - int(ev.get("tickets_sold") or 0))
        out: dict = {
            "@context": "https://schema.org", "@type": "Event",
            "name": ev.get("name") or "", "startDate": ev.get("starts_at"),
            "location": place, "url": url,
            "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
            "eventStatus": "https://schema.org/EventScheduled",
            "offers": {"@type": "Offer", "url": url, "priceCurrency": ev.get("currency") or "USD",
                       "availability": "https://schema.org/InStock" if remaining > 0 else "https://schema.org/SoldOut"},
        }
        if ev.get("ends_at"):
            out["endDate"] = ev["ends_at"]
        if ev.get("doors_at"):
            out["doorTime"] = ev["doors_at"]
        if ev.get("image_url"):
            out["image"] = ev["image_url"]
        if ev.get("description"):
            out["description"] = str(ev["description"])[:300]
        perf = ev.get("performer_names") or []
        if isinstance(perf, list) and perf:
            out["performer"] = [{"@type": "PerformingGroup", "name": str(p)} for p in perf if p]
        return out

    def _bridge_inject_event_meta(shell: str, ev: dict, base: str) -> str:
        """Swap the index.html placeholder tags for this event's and append the
        JSON-LD. Replacements are attribute-level regexes on the tags meta.ts
        also targets, so the SPA's runtime update still finds them."""
        title = f"{ev.get('name') or 'Event'} | Exos"
        desc = (str(ev.get("description") or "")[:200]).replace("\n", " ")
        url = f"{base}/event/{ev['id']}"
        img = ev.get("image_url") or ""
        def set_tag(html_s: str, attr: str, key: str, content: str) -> str:
            pat = re.compile(rf'(<meta\s+{attr}="{re.escape(key)}"\s+content=")[^"]*(")')
            return pat.sub(lambda m: m.group(1) + _html.escape(content, quote=True) + m.group(2), html_s, count=1)
        shell = re.sub(r"<title>[^<]*</title>", f"<title>{_html.escape(title)}</title>", shell, count=1)
        shell = set_tag(shell, "name", "description", desc)
        shell = set_tag(shell, "property", "og:title", title)
        shell = set_tag(shell, "property", "og:description", desc)
        shell = set_tag(shell, "property", "og:type", "event")
        shell = set_tag(shell, "name", "twitter:title", title)
        if img:
            shell = set_tag(shell, "property", "og:image", img)
            shell = set_tag(shell, "name", "twitter:card", "summary_large_image")
        ld = json.dumps(_bridge_event_json_ld(ev, base)).replace("</", "<\\/")
        inject = (f'<link rel="canonical" href="{_html.escape(url, quote=True)}">'
                  f'<meta property="og:url" content="{_html.escape(url, quote=True)}">'
                  f'<script type="application/ld+json" id="vibepass-jsonld">{ld}</script>')
        return shell.replace("</head>", inject + "</head>", 1) if "</head>" in shell else shell

    @router.get("/bridge/event/{event_id}")
    def bridge_event_page(event_id: str, request: Request):
        """SPA shell with this published event's meta + JSON-LD pre-rendered.
        Any failure (bad id, draft, DB down, no keys) serves the plain shell."""
        index_path = os.path.join(get_bridge_dir(), "index.html")
        if not os.path.isfile(index_path):
            raise HTTPException(404, "bridge build not present")
        with open(index_path, "r", encoding="utf-8") as fh:
            shell = fh.read()
        if _UUID_RE.match(event_id or ""):
            try:
                rows = _bridge_rest("exos_public_events", {"id": f"eq.{event_id}", "select": _PUBLIC_EVENT_COLS, "limit": "1"})
                if rows:
                    shell = _bridge_inject_event_meta(shell, rows[0], _bridge_public_base(request))
            except Exception as e:  # noqa: BLE001 — SEO must never break the page
                print(f"[bridge_event_page] pre-render skipped for {event_id}: {e!r}")
        return HTMLResponse(shell)

    @router.get("/bridge/sitemap-events.xml")
    def bridge_events_sitemap(request: Request):
        """Sitemap of published events (≤ 5000 newest by start) for Search Console."""
        base = _bridge_public_base(request)
        rows: list = []
        try:
            rows = _bridge_rest("exos_public_events", {"select": "id,updated_at,starts_at",
                                                       "order": "starts_at.desc.nullslast", "limit": "5000"}) or []
        except Exception as e:  # noqa: BLE001
            print(f"[bridge_events_sitemap] fetch failed: {e!r}")
        items = []
        for ev in rows:
            lastmod = ev.get("updated_at") or ev.get("starts_at")
            items.append("<url><loc>%s/event/%s</loc>%s</url>" % (
                _html.escape(base, quote=True), ev.get("id"),
                f"<lastmod>{_html.escape(str(lastmod)[:10])}</lastmod>" if lastmod else ""))
        body = ('<?xml version="1.0" encoding="UTF-8"?>'
                '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + "".join(items) + "</urlset>")
        return Response(content=body, media_type="application/xml",
                        headers={"Cache-Control": "public, max-age=900"})

    @router.get("/bridge/{page:path}")
    def bridge_static_proxy(page: str):
        """Proxy /bridge/<anything> → static/bridge/<anything>. SPA deep links
        (/bridge/event/123 etc.) fall back to index.html for client-side routing.
        Path-traversal guarded + extension-whitelisted (UI bundle pieces only)."""
        if not page or page in ("", "/"):  # pragma: no cover - shadowed by the explicit /bridge/ index route
            index_path = os.path.join(get_bridge_dir(), "index.html")
            if not os.path.isfile(index_path):
                raise HTTPException(404, "bridge build not present")
            return FileResponse(index_path)
        if ".." in page or page.startswith("/") or "\\" in page:
            raise HTTPException(404, "not found")
        full_path = os.path.join(get_bridge_dir(), page)
        # Real asset → serve it. Whitelist mirrors the /terminal proxy.
        if page.lower().endswith((".html", ".css", ".js", ".map", ".json",
                                   ".svg", ".png", ".jpg", ".jpeg", ".ico",
                                   ".woff", ".woff2", ".webp", ".txt")):
            if not os.path.isfile(full_path):
                raise HTTPException(404, "not found")
            return FileResponse(full_path)
        # Non-asset path (a client route like /bridge/my-tickets) → SPA shell.
        index_path = os.path.join(get_bridge_dir(), "index.html")
        if not os.path.isfile(index_path):
            raise HTTPException(404, "bridge build not present")
        return FileResponse(index_path)


    @router.get("/version.json")
    def version_json():
        """Public deploy-version endpoint — same get_storefront_version() the cache-bust
        pipeline uses, plus the resolution chain that produced it, plus a deploy
        indicator from common Render/Railway env vars. Consumed by nav.js's
        version chip (PR #184) so terminal pages render a real SHA in the topbar
        even though they don't go through _read_storefront_html (which only
        rewrites store pages). Cheap; safe to call cross-origin."""
        return {
            "version": get_storefront_version(),
            "render_commit": os.environ.get("RENDER_GIT_COMMIT") or None,
            "railway_commit": os.environ.get("RAILWAY_GIT_COMMIT_SHA") or None,
            "git_commit": os.environ.get("GIT_COMMIT") or None,
            "render_service_id": os.environ.get("RENDER_SERVICE_ID") or None,
            "render_external_url": os.environ.get("RENDER_EXTERNAL_URL") or None,
            "railway_public_domain": os.environ.get("RAILWAY_PUBLIC_DOMAIN") or None,
            "deployed_at_iso": os.environ.get("RENDER_GIT_COMMIT_TIME") or None,
        }

    return router
