-- Curated calendar for major non-team events that don't have a "team
-- performer" in TEvo to watchlist (F1, NASCAR, tennis, golf majors,
-- Olympics, etc.). We track them by venue + date window. Once we
-- identify the TEvo venue_id, watchlist (kind=venue, ext_id=tevo_venue_id)
-- auto-tracks the venue and collect-listings will pull events at it.
-- Applied to prod 2026-05-09 ~01:30 UTC; this file captures it for git parity.
--
-- Per user spec ("for f1 race performers map to the race instead — 3
-- American races and 1 Canadian annually each 3-4 days long, look up venue
-- or date filter to find actual events"). Same pattern for NASCAR / tennis /
-- golf — manual TEvo event search per major event, then either populate
-- tevo_venue_id here or watchlist the venue directly.

CREATE TABLE IF NOT EXISTS major_event_calendar (
  id              bigint generated by default as identity primary key,
  event_class     text NOT NULL,           -- F1 | NASCAR | Tennis_Major | Golf_Major | Olympics | etc.
  event_name      text NOT NULL,
  venue_name      text NOT NULL,
  venue_city      text,
  venue_country   text DEFAULT 'USA',
  tevo_venue_id   bigint,                  -- populated after TEvo /v9/venues?q= lookup
  window_start    date NOT NULL,
  window_end      date NOT NULL,
  recurrence      text NOT NULL DEFAULT 'annual',
  notes           text,
  active          boolean NOT NULL DEFAULT true,
  added_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mec_window ON major_event_calendar (window_start, window_end) WHERE active;
CREATE INDEX IF NOT EXISTS idx_mec_venue  ON major_event_calendar (venue_name)               WHERE active;

COMMENT ON TABLE  major_event_calendar IS
  'Curated calendar of major non-team events (F1/NASCAR/Tennis/Golf majors). Anchors venue+date filtering for events that don''t have a TEvo team performer.';
COMMENT ON COLUMN major_event_calendar.tevo_venue_id IS
  'Populated manually after a TEvo /v9/venues?q= lookup confirms the id. Once set, watchlist (kind=venue, ext_id=tevo_venue_id) auto-tracks the venue.';

INSERT INTO major_event_calendar (event_class, event_name, venue_name, venue_city, venue_country, window_start, window_end, notes) VALUES
('F1',           'Miami Grand Prix',                       'Miami International Autodrome',                'Miami Gardens', 'USA', '2026-05-01', '2026-05-03', '3-day race weekend'),
('F1',           'Canadian Grand Prix',                    'Circuit Gilles Villeneuve',                    'Montreal',      'CAN', '2026-06-12', '2026-06-14', '3-day race weekend'),
('F1',           'United States Grand Prix',               'Circuit of the Americas',                      'Austin',        'USA', '2026-10-23', '2026-10-25', '3-day race weekend at COTA'),
('F1',           'Las Vegas Grand Prix',                   'Las Vegas Strip Circuit',                      'Las Vegas',     'USA', '2026-11-19', '2026-11-21', '3-day race weekend, night race'),
('NASCAR',       'Daytona 500',                            'Daytona International Speedway',               'Daytona Beach', 'USA', '2026-02-15', '2026-02-15', 'Season opener crown jewel'),
('NASCAR',       'Coca-Cola 600',                          'Charlotte Motor Speedway',                     'Concord',       'USA', '2026-05-24', '2026-05-24', 'Memorial Day classic — longest race'),
('NASCAR',       'Brickyard 400',                          'Indianapolis Motor Speedway',                  'Indianapolis',  'USA', '2026-08-02', '2026-08-02', 'Date varies year to year'),
('NASCAR',       'Bristol Night Race',                     'Bristol Motor Speedway',                       'Bristol',       'USA', '2026-09-12', '2026-09-12', 'Night race playoffs eliminator'),
('NASCAR',       'Talladega 500',                          'Talladega Superspeedway',                      'Talladega',     'USA', '2026-04-26', '2026-04-26', 'Spring restrictor-plate race'),
('Tennis_Major', 'US Open Tennis',                         'USTA Billie Jean King National Tennis Center', 'Queens, NY',    'USA', '2026-08-24', '2026-09-06', '14-day final Slam of year — Arthur Ashe Stadium'),
('Golf_Major',   'The Masters',                            'Augusta National Golf Club',                   'Augusta',       'USA', '2026-04-09', '2026-04-12', 'First major of golf season'),
('Golf_Major',   'PGA Championship',                       'Aronimink Golf Club',                          'Newtown Sq',    'USA', '2026-05-14', '2026-05-17', 'Venue rotates yearly — verify each year'),
('Golf_Major',   'US Open Golf',                           'Shinnecock Hills Golf Club',                   'Southampton',   'USA', '2026-06-11', '2026-06-14', 'Venue rotates yearly — verify each year'),
('Golf_Major',   'The Players Championship',               'TPC Sawgrass',                                 'Ponte Vedra',   'USA', '2026-03-12', '2026-03-15', 'PGA Tour flagship — fixed venue')
ON CONFLICT DO NOTHING;
