-- ============================================================================
-- Migration 20260616240000 — Exos (Bridge / D4): invoicing (pretix parity)
--
-- Lane:     d4 (exos / bridge ticketing infra)
-- Touches:  exos_invoice_counters (W,new), exos_invoices (W,new),
--           exos_next_invoice_number (W,new), exos_tg_invoice + AFTER trigger
--           on exos_checkout_sessions; reads exos_events
-- Pre-reqs: 20260523170000 (checkout sessions), 20260616230000 (session.tax_cents)
--
-- pretix-style invoicing: every fulfilled order gets a sequential, per-ORG
-- invoice number (INV-000001…) and an immutable invoice record (subtotal / tax /
-- total snapshot). Generated by a trigger on fulfillment so the mint fn isn't
-- re-touched; a refund flips the invoice to 'refunded' (credit-note semantics
-- kept simple). The record is the source for a client-side PDF (financial doc,
-- NOT an entry credential — so it does not implicate the rotating-barcode rule).
-- Security mirrors phase-1: deny-by-default RLS; buyer reads own, staff read org.
-- D4 authors; A1 applies to prod.
-- ============================================================================

-- Per-org monotonic counter (one row per org; atomic increment).
CREATE TABLE IF NOT EXISTS public.exos_invoice_counters (
  org_id   uuid PRIMARY KEY REFERENCES public.exos_orgs (id) ON DELETE CASCADE,
  next_seq integer NOT NULL DEFAULT 1 CHECK (next_seq >= 1)
);

CREATE TABLE IF NOT EXISTS public.exos_invoices (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id        uuid NOT NULL REFERENCES public.exos_orgs (id) ON DELETE CASCADE,
  event_id      uuid REFERENCES public.exos_events (id) ON DELETE SET NULL,
  number        text NOT NULL,                 -- e.g. INV-000001 (unique per org)
  session_id    text,                          -- the checkout session it bills
  buyer_id      uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  buyer_email   text,
  currency      text NOT NULL DEFAULT 'usd',
  subtotal_cents integer NOT NULL DEFAULT 0,   -- total - tax
  tax_cents     integer NOT NULL DEFAULT 0,
  total_cents   integer NOT NULL DEFAULT 0,
  status        text NOT NULL DEFAULT 'issued' CHECK (status IN ('issued','refunded','cancelled')),
  issued_at     timestamptz NOT NULL DEFAULT now(),
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, number)
);
CREATE INDEX IF NOT EXISTS exos_invoices_org_idx   ON public.exos_invoices (org_id);
CREATE INDEX IF NOT EXISTS exos_invoices_buyer_idx ON public.exos_invoices (buyer_id);
-- One invoice per session (idempotent against a double fulfillment trigger).
-- Non-partial so ON CONFLICT (session_id) can infer it; NULL session_ids stay
-- distinct under UNIQUE, so manual/comp invoices without a session don't clash.
CREATE UNIQUE INDEX IF NOT EXISTS exos_invoices_session_uniq
  ON public.exos_invoices (session_id);

-- ===========================================================================
-- RLS — buyer reads own; org staff read the org's. No client writes.
-- ===========================================================================
ALTER TABLE public.exos_invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY exos_invoices_sel ON public.exos_invoices FOR SELECT TO authenticated
  USING (buyer_id = auth.uid()
         OR exos_has_org_role(org_id, ARRAY['owner','manager','finance']));
REVOKE ALL ON public.exos_invoices FROM anon, authenticated;
GRANT  SELECT ON public.exos_invoices TO authenticated;
REVOKE ALL ON public.exos_invoice_counters FROM anon, authenticated;   -- service/trigger only

-- ===========================================================================
-- Atomic next-number per org (creates the counter row on first use).
-- ===========================================================================
CREATE OR REPLACE FUNCTION public.exos_next_invoice_number(p_org_id uuid)
RETURNS text
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_seq integer;
BEGIN
  INSERT INTO public.exos_invoice_counters (org_id, next_seq) VALUES (p_org_id, 2)
  ON CONFLICT (org_id) DO UPDATE SET next_seq = public.exos_invoice_counters.next_seq + 1
  RETURNING next_seq - 1 INTO v_seq;
  RETURN 'INV-' || lpad(v_seq::text, 6, '0');
END $$;
REVOKE ALL ON FUNCTION public.exos_next_invoice_number(uuid) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.exos_next_invoice_number(uuid) TO service_role;

-- ===========================================================================
-- Generate / settle the invoice on the session's status transitions.
-- ===========================================================================
CREATE OR REPLACE FUNCTION public.exos_tg_invoice()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE v_tax int; v_total int;
BEGIN
  IF NEW.status = 'fulfilled' AND OLD.status IS DISTINCT FROM 'fulfilled' THEN
    v_total := NEW.amount_cents;
    v_tax   := coalesce(NEW.tax_cents, 0);
    INSERT INTO public.exos_invoices (org_id, event_id, number, session_id, buyer_id,
                buyer_email, currency, subtotal_cents, tax_cents, total_cents)
    VALUES (NEW.org_id, NEW.event_id, public.exos_next_invoice_number(NEW.org_id),
            NEW.session_id, NEW.buyer_uid, NEW.buyer_email, NEW.currency,
            v_total - v_tax, v_tax, v_total)
    ON CONFLICT (session_id) DO NOTHING;   -- idempotent
  ELSIF NEW.status = 'refunded' AND OLD.status IS DISTINCT FROM 'refunded' THEN
    UPDATE public.exos_invoices SET status = 'refunded' WHERE session_id = NEW.session_id;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS exos_checkout_invoice ON public.exos_checkout_sessions;
CREATE TRIGGER exos_checkout_invoice AFTER UPDATE ON public.exos_checkout_sessions
  FOR EACH ROW EXECUTE FUNCTION public.exos_tg_invoice();

COMMENT ON TABLE public.exos_invoices IS
  'D4 mig 20260616240000: pretix-style invoices. Sequential per-org number
   (exos_next_invoice_number) + immutable subtotal/tax/total snapshot, generated
   on fulfillment by exos_checkout_invoice; refund flips status. Source for a
   client-side PDF (a financial doc, not an entry credential).';
